server:
  port: 8081
logging:
  level:
    com.alibaba.otter.canal.client.adapter.hbase: DEBUG
    com.alibaba.otter.canal.client.adapter.es: DEBUG
    com.alibaba.otter.canal.client.adapter.rdb: DEBUG
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

#canal.conf:
#  canalServerHost: 127.0.0.1:11111
#  zookeeperHosts: slave1:2181
#  bootstrapServers: slave1:6667 #or rocketmq
#  flatMessage: true
#  canalInstances:
#  - instance: example
#    groups:
#    - outAdapters:
#      - name: logger
#      - name: rdb
#        key: oracle1
#        properties:
#          jdbc.driverClassName: oracle.jdbc.OracleDriver
#          jdbc.url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
#          jdbc.username: mytest
#          jdbc.password: m121212
#      - name: rdb
#        key: postgres1
#        properties:
#          jdbc.driverClassName: org.postgresql.Driver
#          jdbc.url: jdbc:postgresql://localhost:5432/postgres
#          jdbc.username: postgres
#          jdbc.password: 121212
#      - name: hbase
#        properties:
#          hbase.zookeeper.quorum: 127.0.0.1
#          hbase.zookeeper.property.clientPort: 2181
#          zookeeper.znode.parent: /hbase
#      - name: es
#        hosts: 127.0.0.1:9300
#        properties:
#          cluster.name: elasticsearch
#  mqTopics:
#  - mqMode: kafka
#    topic: example
#    groups:
#    - groupId: g2
#      outAdapters:
#      - name: logger
#  mqTopics:
#  - mqMode: rocketmq
#    topic: example
#    groups:
#    - groupId: g2
#      outAdapters:
#      - name: logger

#adapter.conf:
#  datasourceConfigs:
#    defaultDS:
#      url: jdbc:mysql://127.0.0.1:3306/mytest?useUnicode=true
#      username: root
#      password: 121212
#  adapterConfigs:
#  - hbase/mytest_person2.yml
#  - es/mytest_user.yml
#  - rdb/mytest_user.yml
