server:
  port: 8081

canal.conf:
  canalServerHost: 127.0.0.1:11111
  #zookeeperHosts: slave1:2181
  #bootstrapServers: localhost:9092 #or rocketmq nameservers:host1:9876;host2:9876
  flatMessage: false

  canalInstances:
  - instance: example
    adapterGroups:
    - outAdapters:
      - name: logger
#      - name: hbase
#        hosts: slave1:2181
#        properties: {znodeParent: "/hbase-unsecure"}

adapter.conf.path:
  adapterConfigs:
  - hbase/mytest_person2.yml